#! /bin/bash

for file in "${@}"

do
x=$(cat ${file} | head -n 2 | tail -n 1 | gawk '{print $2}' | ./Python/square.py)
xavg=$(cat ${file} | gawk -v x="${starttime}" 'x + 10000 > $1, NF > 1 {print $2}' | tail -n +2 | ./Python/avg.py | ./Python/square.py)
distance=$(echo "${x} + ${xavg} | bc | ./Python/sqrt.py)
echo "${distance}"

done
