#! /bin/bash

for file in "${@}"

do
starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")
xavg=$(cat ${file} | gawk -v x="${starttime}" 'x + 10000 > $1, NF > 1 {print $2}' | tail -n +2 | ./Python/avg.py)
yavg=$(cat ${file} | gawk -v x="${starttime}" 'x + 10000 > $1, NF > 1 {print $3}' | tail -n +2 | ./Python/avg.py)
cat ${file} | tail -n +2 | gawk -v x="${starttime}" -v xavg="${xavg}" -v yavg="${yavg}" 'x + 10000 > $1, NF > 1 {print ($2 - xavg)**2, ($3 - yavg)**2}' | gawk '{print ($1 + $2)**0.5}'
done
