#! /bin/bash

for file in  "${@}"

do
starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")
xavg=$(cat ${file} | gawk -v x="${starttime}" 'x + 1000 > $1, NF > 1 {print $2}' | tail -n +2 | ./Python/avg.py)
yavg=$(cat ${file} | gawk -v x="${starttime}" 'x + 1000 > $1, NF > 1 {print $3}' | tail -n +2 | ./Python/avg.py)

xstd=$(cat ${file} | gawk -v x="${starttime}" 'x + 1000 > $1, NF > 1 {print $2}' | tail -n +2 | ./Python/stddev.py)
ystd=$(cat ${file} | gawk -v x="${starttime}" 'x + 1000 > $1, NF > 1 {print $3}' | tail -n +2 | ./Python/stddev.py)
xstddev=$(cat ${file} | gawk -v x="${starttime}" 'x + 1000 > $1, NF > 1 {print $2}' | tail -n +2 | ./Python/stddev.py | ./Python/square.py)
ystddev=$(cat ${file} | gawk -v x="${starttime}" 'x + 1000 > $1, NF > 1 {print $3}' | tail -n +2 | ./Python/stddev.py | ./Python/square.py)
totstd=$(echo "${xstddev} + ${ystddev}" | bc | ./Python/sqrt.py)

echo "${file} ${xavg} ${yavg} ${xstd} ${ystd} ${totstd}"
done | column -t
