#! /bin/bash
echo "sort by x-avg"
for file in "${@}"
do 
./avg-stddev-10 ${file}
done | column -t | sort -n -k 2
echo "sort by y-avg"
for file in "${@}"
do 
./avg-stddev-10 ${file}
done | column -t | sort -n -k 3
echo "sort by xstddev"
for file in "${@}"
do 
./avg-stddev-10 ${file}
done | column -t | sort -n -k 4
echo "sort by ystddev"
for file in "${@}"
do 
./avg-stddev-10 ${file}
done | column -t | sort -n -k 5
echo "sort by totstddev"
for file in "${@}"
do 
./avg-stddev-10 ${file}
done | column -t | sort -n -k 6
