#! /bin/bash

for file in "${@}"

do
starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")
xavg=$(cat ${file} | gawk -v x="${starttime}" 'x + 10000 > $1, NF > 1 {print $2}' | tail -n +2 | ./Python/avg.py)
xdistance=$(cat ${file} | gawk -v x="${starttime}" 'x + 10000 > $1, NF > 1 {print $2}' | gawk -v xavg="${xavg}" '{diff = xavg - $1}; {xsq = diff**2}; {print xsq}') 
echo "${xdistance}"

done
