#! /bin/bash

for file in "${@}"

do
starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")
yavg=$(cat ${file} | gawk -v x="${starttime}" 'x + 10000 > $1, NF > 1 {print $3}' | tail -n +2 | ./Python/avg.py)
ydistance=$(cat ${file} | gawk -v x="${starttime}" 'x + 10000 > $1, NF > 1 {print $3}' | gawk -v yavg="${yavg}" '{diff = yavg - $1}; {ysq = diff**2}; {print ysq}') 
echo "${ydistance}"

done
